-- GENERATED by art-src/pack.py — do not hand-edit.
-- name -> {x, y, w, h} rect on sprites.png. Re-run the packer,
-- don't patch this file.
return {
  TitleScreen = { x = 1, y = 1, w = 640, h = 320 },
}
