#!/usr/bin/env python3
"""Stitches every finished art asset in art-src/ready/ into
sky-islands/sprites.png and regenerates sky-islands/defs/art.lua.

The "smart" packing is Aseprite's own CLI packer (--sheet-type packed),
not a hand-rolled one — it bin-packs mixed sizes tighter than a fixed
grid would, and emits the name->rect JSON we need in the same command.

Folder convention (see art-src/README.md):
  rough/<zone>/   work in progress, exploration, references. Never packed.
  ready/<zone>/   finished .aseprite/.ase/.png files. Packed on every run.
Move a file from rough/ to ready/ when it's done — that's the only gate.

Usage:
  python3 art-src/pack.py            pack into the real sprites.png
  python3 art-src/pack.py --draft    pack into art-src/_build/ instead
  python3 art-src/pack.py --max-size 2048   override the safety cap (default 4096)

Safety cap default of 4096 matches the budget decision in
proposals/art-pipeline.md: half the engine's own tested-safe ceiling
(8192), chosen because WebGL on older/mobile GPUs commonly caps lower
and a sheet past the limit uploads clamped with NO error — silent
black sprites past that point. This script warns loudly instead.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
READY = os.path.join(ROOT, "ready")
BUILD = os.path.join(ROOT, "_build")
SKY = os.path.join(REPO, "sky-islands")

# Reference footprints from proposals/art-pipeline.md, used only to turn
# leftover budget into a human-readable "roughly how many more of X"
# estimate. Pure area division, not a packing simulation — real capacity
# will be a bit lower once padding/fragmentation are accounted for.
INTERLUDE_SIZE = (640, 228)  # visible band above the text panel
PORTRAIT_SIZE = (128, 128)   # 96x96 native, padded to a round grid cell

ASEPRITE_CANDIDATES = [
    os.path.expanduser(
        "~/Library/Application Support/Steam/steamapps/common/Aseprite/"
        "Aseprite.app/Contents/MacOS/aseprite"
    ),
    os.path.expanduser("~/Applications/Aseprite.app/Contents/MacOS/aseprite"),
    "aseprite",
]

EXTS = (".aseprite", ".ase", ".png")


def find_aseprite():
    for candidate in ASEPRITE_CANDIDATES:
        path = candidate if os.sep in candidate else None
        if path and os.path.isfile(path):
            return path
        if path is None:
            from shutil import which

            found = which(candidate)
            if found:
                return found
    return None


def gather_sources():
    files = []
    for zone in sorted(os.listdir(READY)):
        zone_dir = os.path.join(READY, zone)
        if not os.path.isdir(zone_dir):
            continue
        for name in sorted(os.listdir(zone_dir)):
            if name.startswith("."):
                continue
            if os.path.splitext(name)[1].lower() in EXTS:
                files.append(os.path.join(zone_dir, name))
    return files


def run_aseprite(aseprite_bin, files, sheet_out, data_out):
    # Deliberately no --sheet-width/--sheet-height: packed mode auto-sizes
    # to the tightest fit for whatever content actually exists. Forcing a
    # fixed size would pad a two-file test run out to a mostly-empty 4096²
    # PNG. The safety cap is enforced after the fact instead (see main()).
    cmd = [
        aseprite_bin, "-b",
        *files,
        "--sheet-type", "packed",
        "--trim",
        "--border-padding", "1",
        "--shape-padding", "1",
        "--sheet", sheet_out,
        "--data", data_out,
        "--format", "json-array",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("aseprite failed:", result.stderr or result.stdout, file=sys.stderr)
        sys.exit(1)
    if result.stdout.strip():
        print(result.stdout.strip())


def write_art_lua(data_out, lua_out):
    with open(data_out) as f:
        data = json.load(f)
    entries = []
    sources = {}  # name -> source path, for the duplicate-name error message
    for frame in data["frames"]:
        name = os.path.splitext(os.path.basename(frame["filename"]))[0]
        if name in sources:
            print(
                f"\n!! ERROR: two source files both name the sprite "
                f"'{name}':\n"
                f"     {sources[name]}\n"
                f"     {frame['filename']}\n"
                f"   Names are the Lua key (art.{name}) and must be unique "
                f"across ALL zones, not just within one folder. A duplicate "
                f"silently overwrites in the Lua table with no error at "
                f"runtime — rename one of the files and re-run.",
                file=sys.stderr,
            )
            sys.exit(1)
        sources[name] = frame["filename"]
        r = frame["frame"]
        entries.append((name, r["x"], r["y"], r["w"], r["h"]))
    entries.sort(key=lambda e: e[0])

    lines = [
        "-- GENERATED by art-src/pack.py — do not hand-edit.",
        "-- name -> {x, y, w, h} rect on sprites.png. Re-run the packer,",
        "-- don't patch this file.",
        "return {",
    ]
    for name, x, y, w, h in entries:
        lines.append(
            f'  {name} = {{ x = {x}, y = {y}, w = {w}, h = {h} }},'
        )
    lines.append("}")
    lines.append("")
    with open(lua_out, "w") as f:
        f.write("\n".join(lines))
    return entries


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--draft", action="store_true",
                     help="write to art-src/_build/ instead of sky-islands/")
    ap.add_argument("--max-size", type=int, default=4096,
                     help="safety cap for either sheet dimension (default 4096)")
    ap.add_argument("--tile-size", type=int, default=32,
                     help="assumed square tile size for the remaining-budget "
                          "estimate (default 32; try 16 or 64 for other plans)")
    args = ap.parse_args()

    files = gather_sources()
    if not files:
        print("Nothing in art-src/ready/*/ yet — nothing to pack.")
        return

    aseprite_bin = find_aseprite()
    if not aseprite_bin:
        print("Couldn't find the aseprite CLI binary. Checked:", file=sys.stderr)
        for c in ASEPRITE_CANDIDATES:
            print("  ", c, file=sys.stderr)
        sys.exit(1)

    os.makedirs(BUILD, exist_ok=True)
    data_out = os.path.join(BUILD, "sheet.json")
    if args.draft:
        sheet_out = os.path.join(BUILD, "sprites_draft.png")
        lua_out = os.path.join(BUILD, "art_draft.lua")
    else:
        sheet_out = os.path.join(SKY, "sprites.png")
        lua_out = os.path.join(SKY, "defs", "art.lua")

    print(f"Packing {len(files)} source file(s) with {aseprite_bin}")
    for f in files:
        print("  ", os.path.relpath(f, REPO))

    run_aseprite(aseprite_bin, files, sheet_out, data_out)
    entries = write_art_lua(data_out, lua_out)

    with open(data_out) as f:
        meta = json.load(f)["meta"]
    w, h = meta["size"]["w"], meta["size"]["h"]
    used_pct = (w * h) / (args.max_size * args.max_size) * 100
    print(f"\nWrote {os.path.relpath(sheet_out, REPO)}: {w}x{h}, "
          f"{len(entries)} entries")
    print(f"Wrote {os.path.relpath(lua_out, REPO)}")
    print(f"Budget: {used_pct:.1f}% of the {args.max_size}x{args.max_size} "
          f"theoretical canvas ({w * h:,} / {args.max_size * args.max_size:,} px²)")

    remaining = max(0, args.max_size * args.max_size - w * h)
    interlude_area = INTERLUDE_SIZE[0] * INTERLUDE_SIZE[1]
    portrait_area = PORTRAIT_SIZE[0] * PORTRAIT_SIZE[1]
    tile_area = args.tile_size * args.tile_size
    remaining_interludes = remaining // interlude_area
    remaining_portraits = remaining // portrait_area
    remaining_tiles = remaining // tile_area
    print(f"Remaining ({100 - used_pct:.1f}% of budget) could hold roughly "
          f"{remaining_interludes:,} more interludes "
          f"({INTERLUDE_SIZE[0]}x{INTERLUDE_SIZE[1]}), OR "
          f"{remaining_portraits:,} more portraits "
          f"({PORTRAIT_SIZE[0]}x{PORTRAIT_SIZE[1]}), OR "
          f"{remaining_tiles:,} more {args.tile_size}x{args.tile_size} tiles "
          f"— these are alternatives, not additive; area estimate, not a "
          f"packing guarantee.")

    if w > args.max_size or h > args.max_size:
        print(f"\n!! WARNING: sheet is {w}x{h}, over the {args.max_size} "
              f"safety cap. A texture past a device's GPU limit uploads "
              f"clamped — sprites sourced beyond that point render BLACK "
              f"with no error, especially on web/mobile. Trim content or "
              f"raise --max-size deliberately, don't ignore this.",
          file=sys.stderr)


if __name__ == "__main__":
    main()
